# fly.toml app configuration file generated for backend-red-morning-8039 on 2025-05-24T09:47:34+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-red-morning-8039'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-4x'
